// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSgo8gzOtIvpiCiGuIm41kJMgvpMpx9T4',
    appId: '1:461088315296:android:443815194755807970f6c5',
    messagingSenderId: '461088315296',
    projectId: 'modul-7-2',
    storageBucket: 'modul-7-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRfWUYo45XdnYpmBr7UcAdj08us6EBYnc',
    appId: '1:461088315296:ios:9ae2f0ba4d71628f70f6c5',
    messagingSenderId: '461088315296',
    projectId: 'modul-7-2',
    storageBucket: 'modul-7-2.appspot.com',
    androidClientId: '461088315296-r2naqsccb82ckcs6absdcq3epv2acc2d.apps.googleusercontent.com',
    iosClientId: '461088315296-qo1sqagulfikiuuk55qfk9l391kmi98u.apps.googleusercontent.com',
    iosBundleId: 'com.example.safiyyaCooking',
  );
}
